
// import { Inter } from 'next/font/google'
// import { ChakraProvider } from '@chakra-ui/react'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
"use client"
import { ChakraProvider } from '@chakra-ui/react'
import Navbar from './components/Navbar'
import FooterPage from './components/Footer'


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          <Navbar />
          {children}
          
        </ChakraProvider>
        
        </body>
    </html> 
  )
}
